### ISSUE TITLE
AJS.progressBars.update deprecation

### ISSUE THREAD

**Issue by Mihailoff** [spartez/vue-aui#22]
```
DEPRECATED JS - AJS.progressBars.update has been deprecated since 7.7.0 and will be removed in a future release. Use the <aui-progressbar> web component instead  
     at o.setProgerssIndicator (vue-aui@1.0.7/dist/static/js/vue-aui.min.js:5:48170)
```

**Comment by damienix** [comment]
That's true, what's the issue here?

Since AUI 7.7 Atlassian deprecated this method and provided web component to use as a progress bar. It's here https://docs.atlassian.com/aui/7.9.9/docs/progress-indicator.html

I've updated the docs to indicate that https://spartez.github.io/vue-aui/#/components/progress-indicator for future `vue-aui` users.

Is there anything else I can help you with?
