### ISSUE TITLE
VaNavItem don't have a v-on:click

### ISSUE THREAD

**Issue by guastallaigor** [spartez/vue-aui#29]
### Versions and Environment
Vue-aui: ^1.0.8
Vue: 2.5.17
Browser: Google Chrome 69.0.3497.100 64 bits
OS: Linux (Ubuntu) 16.04

### Steps to reproduce
1. Copy the `<va-nav-item>` from the [AUI Naviagation Docs](https://spartez.github.io/vue-aui/#/components/navigation).
2. Add `@click="method"` on it.

```html
<va-nav-item name="Entry" @click="showHide" icon="star" href="#/" :selected="$route.path === '/'"></va-nav-item>
```

### Expected Behavior
Should activate the method and go to the route.path provided.

### Actual Behavior

The method is never called.

### Code pen

https://codepen.io/guastallaigor/pen/Eddxoz

---

### Additional Comments:
In my scenario, I want to hide the sidebar when I click on a `<va-nav-item>` so I believe it needs a `v-on:click` on it.

**Comment by damienix** [comment]
The reason it doesn't work is that you would have to use `@click.native` to actually handle the click of the HTML element instead of Vue component. I agree though that delegating this event makes sense for convenience.

I even did the same for button events 
https://github.com/spartez/vue-aui/blob/c94c58f41586d9d053cc16a47d6c4745af172bdb/src/components/buttons/Button.js#L10-L20
