### ISSUE TITLE
AUI Dropdown2 support ?

### ISSUE THREAD

**Issue by guvial** [spartez/vue-aui#3]
Hi,
I have started using vue.js for JIRA add-on development. Your project is very interesting for me, I will use start using it ASAP.
I need to "wrap" the dropdown2 aui component. Have you already planned to add this component in your lib ? an idea about the better way to be able to use dropdown2 in vue.js ?
Cheers,
Guillaume

**Comment by damienix** [comment]
Hi,

actually I have that on my todo list but honestly, I didn't need this so there is no implementation. 

But let's take https://docs.atlassian.com/aui/latest/docs/dropdown.html as reference as it's the newest dropdown. For me, the problem here is - there is not too much to simplify. Do you have something that makes you think that dropdown is worth wrapping at all? If there are specific problems that Vue can solve, I'm willing to take a look into that. If it's gonna just add another abstraction layer, I'm not sure...

**Comment by guvial** [comment]
Hi,
I finally found a way to use dropdown2 without wrapping it. I am quite new to vue.js and I still have some bad "JQuery spaghetti code" habits... ;-)

I have also started using your select2 components and they are working perfectly. Thanks a lot to share this lib, good job ! ;-) 

Enjoy your day ! 

Guillaume

**Comment by damienix** [comment]
I'm happy to hear that you have your problem solved :)

Select2 components were actually the initial reason why I have created this library. We were copying them over again and the code between the projects started to diverge. Now the is only one source of truth: vue-aui.

Looking forward to hearing some ideas with components that could actually simplify the code, once you get familiar with Vue.

Good luck :)
Damian
